/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const MenuCategory = IDL.Record({
  'category' : IDL.Text,
  'items' : IDL.Vec(MenuItem),
});
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'specialRequests' : IDL.Text,
  'time' : IDL.Text,
  'timestamp' : Time,
  'partySize' : IDL.Nat,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addContactSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addMenuCategory' : IDL.Func([IDL.Text, IDL.Vec(MenuItem)], [], []),
  'addReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
  'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const MenuCategory = IDL.Record({
    'category' : IDL.Text,
    'items' : IDL.Vec(MenuItem),
  });
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'specialRequests' : IDL.Text,
    'time' : IDL.Text,
    'timestamp' : Time,
    'partySize' : IDL.Nat,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addContactSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addMenuCategory' : IDL.Func([IDL.Text, IDL.Vec(MenuItem)], [], []),
    'addReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuCategory)], ['query']),
    'getReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };