/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface MenuCategory { 'category' : string, 'items' : Array<MenuItem> }
export interface MenuItem {
  'name' : string,
  'description' : string,
  'price' : number,
}
export interface Reservation {
  'id' : bigint,
  'contact' : string,
  'date' : string,
  'name' : string,
  'specialRequests' : string,
  'time' : string,
  'timestamp' : Time,
  'partySize' : bigint,
}
export interface Review {
  'id' : bigint,
  'date' : Time,
  'name' : string,
  'comment' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addContactSubmission' : ActorMethod<[string, string, string], bigint>,
  'addMenuCategory' : ActorMethod<[string, Array<MenuItem>], undefined>,
  'addReservation' : ActorMethod<
    [string, string, string, bigint, string, string],
    bigint
  >,
  'addReview' : ActorMethod<[string, bigint, string], bigint>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getMenu' : ActorMethod<[], Array<MenuCategory>>,
  'getReservations' : ActorMethod<[], Array<Reservation>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];